### PR TITLE
Componentification, part 3

### PR DESCRIPTION
**Pull request by nschloe**
Just moving code around.

### CODE REVIEW

**Comment by andrenarchy** [comment]
Something funny happened to our whitespaces:
```html
<!-- new -->
<a href="./signup?returnPath=/" class="btn btn-primary">Sign up </a><a href="./login?returnPath=/" class="btn btn-default">Log in</a>

<!-- old -->
<a href="./signup?returnPath=/" class="btn btn-primary">Sign up</a> <a href="./login?returnPath=/" class="btn btn-default">Log in</a>
```
This results in
screenshot from 2016-03-18 16-20-44
instead of
screenshot from 2016-03-18 16-20-31

@nschloe do you know why this happens?

**Comment by andrenarchy** [comment]
Can you also move the `navbar-user` and `navbar-search` templates to the component dir? The directives haven't been touched by this PR but it would be consistent. Maybe there are more templates in `shared` that should be moved to their component code?

**Comment by nschloe** [comment]
@andrenarchy The issues you mentioned are addressed now.

**Comment by andrenarchy** [comment]
The spacing issue is also in master. Can you revert your "fix"? :D

I'd then merge this PR and we try to find a solution for the HTML transmogrification in a separate branch.

**Comment by nschloe** [comment]
> Can you revert your "fix"? 

Is a revert really required? After all, it doesn't change the behavior at all. :D

**Comment by andrenarchy** [comment]
No, it's just that the HTML looks a bit weird. Actually, HTML always looks weird. Thanks, XML. :smile:

**Pull request merged**
