### PR TITLE
Add deep links

### PR DESCRIPTION
**Pull request by andrenarchy**
Allows any visitor (authenticated and unauthenticated) to create a deep link for a text selection:

screenshot from 2016-09-13 11-15-30

Opening the link will send the user directly to the selected text. Furthermore, the margin discussion draft is displayed in the exact same way as if the user selected the text her/himself:

screenshot from 2016-09-13 11-15-58

Example link: https://dev.paperhive.org/frontend/deep-links/documents/N2iCMzBfgu3p?a=s:KXnuMgplxE47

### CODE REVIEW

**Comment by andrenarchy** [comment]
@jengeb i fixed the misplaced popover by using `auto bottom-left`. What is the issue with the selection of paragraph 1? How can I reproduce this (and on which document)?

**Comment by jengeb** [comment]
Try to select the whole 1st paragraph of the following document: https://dev.paperhive.org/frontend/deep-links/documents/N2iCMzBfgu3p?a=s:KXnuMgplxE47

**Comment by andrenarchy** [comment]
The selection issue is treated seperately since it already exists in master.

Summary: only the `overflow: hidden` vs popup issue remains to be fixed.

**Comment by andrenarchy** [comment]
`overflow: hidden` has been removed. The expected effect is that pdf-pages may overflow during window resizing.

**Pull request merged**
