### PR TITLE
Make dev toolchain compatible with Windows

### PR DESCRIPTION
**Pull request by andrenarchy**
@lena-mari88 please check if the dev toolchain now also works on Windows (and let me know here). :smile: 

Most important commands to check: `npm run build` and `npm run watch`.

### CODE REVIEW

**Comment by lena-mari88** [comment]
Command is now working on Windows, too. Only issue I've come across was the error when trying to run `npm run watch`, which didn't work before running `npm run build:dev:html`
This only worked after submitting the command multiple times, after that everything worked great!

**Comment by andrenarchy** [comment]
Maybe nodemon behaves differently on Windows. I changed `watch` so it runs `build:dev:*` before going into watch mode. This has the additional benefit of cleaner (serial) log output.

@lena-mari88 can you check if `npm run watch` works as expected after wiping the build data (`npm run clean`)?

**Comment by lena-mari88** [comment]
@andrenarchy Great fix! It is working fine now.

**Comment by andrenarchy** [comment]
Perfect, thx for testing! :smile:

**Pull request merged**
