### PR TITLE
deps update

### PR DESCRIPTION
**Pull request by nschloe**
We might want to wait for leaflet to release, cf. [here](https://github.com/tombatossals/angular-leaflet-directive/issues/871) and
```
+    "angular-leaflet-directive": "git@github.com:tombatossals/angular-leaflet-directive.git#3204bf304d74930704d2c3a6553c4da1c3952ee4",
```

### CODE REVIEW

**Comment by andrenarchy** [comment]
angular-leaflet-directive has a new release, do you want to update?

**Comment by nschloe** [comment]
http://www.dailymotion.com/video/xgtkf_abba-i-do-i-do-i-do-i-do_music

**Comment by nschloe** [comment]
Due to the updates, we now get a warning on the console reading
```
tooltip-html-unsafe is now deprecated. Use tooltip-html or tooltip-template instead.
```
I wasn't able to resolve it at this point, but re can worry about it later.

**Comment by andrenarchy** [comment]
This is the copyright/license information tooltip. I'll prepare a commit later...

**Comment by nschloe** [comment]
Yeap right. When I simply use `tooltip-html` as suggested in the warning, I'm getting
```
Uncaught Error: [$parse:lexerr] Lexer Error: Unterminated quote at columns 35-852 ['s html() -->
[...]
```
upon clicking on the tooltip.

**Comment by andrenarchy** [comment]
The tooltip warning is gone by using `tooltip-template`. The `attribution` directive now actually is much cleaner because I could remove all the `watch`-magic.

But there are still issues that need to be resolved before merging:

* Carousel doesn't work, see angular-ui/bootstrap#3811.
* the `typeahead` directive from angular-bootstrap throws the warning

    ```
bindHtmlUnsafe is now deprecated. Use ngBindHtml instead
```
    when searching for an article, see angular-ui/bootstrap#2884.
* `pdfjs` throws the warning

    ```
The provided value 'moz-chunked-arraybuffer' is not a valid enum value of interface XMLHttpRequestResponseType.
```
    Issue mozilla/pdf.js/issues/6174 throws the same message, but I'm not sure if it's related.

**Comment by andrenarchy** [comment]
angular-bootstrap 0.13.2 was [released yesterday](https://github.com/angular-ui/bootstrap/blob/master/CHANGELOG.md). It remains to check if all of our issues are solved with the new release. :)

**Comment by andrenarchy** [comment]
The carousel works again but not as expected (content slides to the wrong side). The log messages remain.

@nschloe does it break anything? :)

**Comment by nschloe** [comment]
For me, the carousel does work as expected. 
Other than that, I find everything else working as expected as well.

**Comment by nschloe** [comment]
The latest update brings a proper carousel fix.

**Comment by nschloe** [comment]
The pdf.js warning is reported at https://github.com/mozilla/pdf.js/issues/6306.

**Comment by nschloe** [comment]
Apparently, it's expected normal to get the warning, cf. https://github.com/mozilla/pdf.js/issues/6306#issuecomment-130416712.

Since the typeahead deprecation warning is also being worked on, I'd consider this PR good to go for now.

**Comment by andrenarchy** [comment]
Alright, now MathJax brings in an error when comments are rendered on, see [here](https://paperhive.org/dev/frontend/branches/deps/articles/555a204bc387b7cf08ae644d). It tries to load `about:blank` as a font which results 
```
Font from origin 'null' has been blocked from loading by Cross-Origin Resource Sharing policy: Received an invalid response. Origin 'https://paperhive.org' is therefore not allowed access.
```

**Comment by nschloe** [comment]
Upstream claims "this isn't an error", cf. https://github.com/mathjax/MathJax/issues/926.

**Pull request merged**
