### PR TITLE
Websockets

### PR DESCRIPTION
**Pull request by jengeb**
Use websockets in document controller for synchronizing discussions and replies.

### CODE REVIEW

**Comment by andrenarchy** [comment]
@nschloe This branch needs the `websockets` backend branch which should be merged first. I'll write a few tests there and file the PR asap today. But feel free to review this frontend PR before! :)

**Comment by nschloe** [comment]
Thanks for the update. I'll look at it, but won't merge it until the backend it ready.

**Comment by andrenarchy** [comment]
After merging the websockets backend branch, the `apiUrl` in `config.json.default` in this PR should point to the master branch again.

**Comment by nschloe** [comment]
>  the apiUrl in config.json.default in this PR should point to the master branch again.

Go for it.

**Comment by nschloe** [comment]
Thanks everyone, great work.

**Pull request merged**
